### ISSUE TITLE
Error on big .psd file

### ISSUE THREAD

**Issue by mikri2017** [PsdPlugin/PsdPlugin#1]
Error when open .psd file 32.2 Mb
P.S. In English error: Not enough memory.

![image](https://user-images.githubusercontent.com/25917800/31372727-5fff7078-adc1-11e7-88fb-6a9a4312cb05.png)

**Comment by taoyue** [comment]
PSD files can blow up by 100 times or more when loaded into Paint.NET.  Please see "Insufficient memory due to too many layers": http://www.psdplugin.com/docs/compatibility-with-photoshop/
