### ISSUE TITLE
Support for layer comps

### ISSUE THREAD

**Issue by killerog** [PsdPlugin/PsdPlugin#10]
Hi, 

Would it be possible to add support for layer comps to the plugin in some way? Or is that outside of the scope of this plugin?

Thanks, Rogier.

**Comment by taoyue** [comment]
Paint.NET doesn't have layer comps, so the user wouldn't be able to switch between them.  It's not very useful to implement something in the PSD Plugin if it doesn't exist in Paint.NET.
