### ISSUE TITLE
donation using PayPal: not possible ?

### ISSUE THREAD

**Issue by billwoo** [PsdPlugin/PsdPlugin#15]
fyi: I just tried to send you a small donation and got an error message saying donations were not supported in "this country." I am in Thailand.

Thanks for this excellent plug-in !

**Comment by taoyue** [comment]
PayPal Thailand is currently being relaunched due to government regulations.  There may be disruptions to functionality while this is going on.

Thanks for the note.  It's good to hear that you found the plugin to be useful.
