### ISSUE TITLE
Plugin fails to open certain files

### ISSUE THREAD

**Issue by TurklerRS** [PsdPlugin/PsdPlugin#16]
this plugin is really useful. but recently some .psd files I've recieved through discord fail to open
![image](https://user-images.githubusercontent.com/49252967/146692097-3f9ea8e1-677f-46a5-b844-5972235299c3.png)
see image above
odd thing is that irfanview has no issue opening it, so it's definitely an issue on this plugin's end
![image](https://user-images.githubusercontent.com/49252967/146692147-4daae319-0337-4807-9567-794e38cfa893.png)

here's the file itself just in case you want tot try it out
https://drive.google.com/file/d/1NlDJSVud6Ub5FLkkqf3V4YXjB7eGK4BM/view?usp=sharing

**Comment by neoncube2** [comment]
I'm getting this error message, too. Let me know if having another test case to reproduce would be helpful :)

**Comment by taoyue** [comment]
Fixed in 02d5c1c.
