### ISSUE TITLE
Paint.net not recognizing plugin

### ISSUE THREAD

**Issue by Criticaldiamonds** [PsdPlugin/PsdPlugin#2]
I downloaded the newest version of both pdn and the plugin and put the plugin in the FileTypes folder, but I don't see anything new in the "Open" dialog, and I can't open PDN files

**Comment by taoyue** [comment]
Please post screenshots of File Explorer, View-Details, opened to the following directories:

- C:\Program Files\paint.net
- C:\Program Files\paint.net\Effects
- C:\Program Files\paint.net\FileTypes

**Comment by taoyue** [comment]
Closing due to lack of response.
