### ISSUE TITLE
Keep PSD layer groups/folders compatability

### ISSUE THREAD

**Issue by ievgennaida** [PsdPlugin/PsdPlugin#6]
I know that Paint.NET has only one level of layers but while you import layers like groups "Layer Group: {0}" and "End Layer Group: {0}" it would be perfect to restore original layers when saved!

I use both programs and as user I am not aware that photoshop file will become flat.
Please add checkbox "keep layers" to preserve existing layers when file is saved.

**Comment by taoyue** [comment]
The PSD Plugin follows a bright-line rule: Features that exist in both Paint.NET and Photoshop can be both loaded and saved.  Whenever Paint.NET gets layer groups, the PSD Plugin will add that feature.

Creating layer groups based on the layer names turns Paint.NET into a non-WYSIWYG image editor.  The layer names become interpreted as markup.  Layer groups don't blend correctly in Paint.NET, so the file that's saved could look different than what's shown on screen.

**Comment by ievgennaida** [comment]
Hi, thanks for your answer.
In other hand if you about to open and save the original PSD you will always brake the original structure. 
I am struggling with this while few people use Photoshop and few are Paint.NET.
Anyway I have added it only as an option so they are free to enable or disable this feature.
