### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [PsdPlugin/PsdPlugin#9]
The last version is from 2016, an new soon?

**Comment by Neustradamus** [comment]
Last version does not work with last Paint.NET version.

**Comment by taoyue** [comment]
I just did a clean install of Paint.NET 4.2.1 and PSD Plugin 2.5.0 in a fresh Windows 10 VM, and opened a PSD file successfully.

Please describe what kind of trouble you're having.  Attach screenshots if it will help.
